# Generated by Django 4.0.4 on 2022-05-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=10)),
                ('production_date', models.DateField()),
            ],
        ),
    ]
