# Generated by Django 4.0.4 on 2022-05-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0002_profil_remove_gift_party_gift_party_alter_party_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='party',
            name='start_date',
        ),
        migrations.AddField(
            model_name='party',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='party_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='party_time',
            field=models.TimeField(null=True),
        ),
    ]
