# Generated by Django 4.0.4 on 2022-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0003_remove_party_end_date_remove_party_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='comments',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='number_of_adults',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='number_of_children',
            field=models.IntegerField(null=True),
        ),
    ]
