# Generated by Django 4.0.4 on 2022-06-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0005_gift_comments_gift_gift_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='gift',
            name='party',
            field=models.ManyToManyField(through='imprezy.PartyGift', to='imprezy.party'),
        ),
        migrations.AddField(
            model_name='partygift',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezy.gift'),
        ),
        migrations.AddField(
            model_name='partygift',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezy.party'),
        ),
    ]
