# Generated by Django 4.0.4 on 2022-06-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0007_alter_gift_party_delete_partygift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='party',
        ),
    ]
