# Generated by Django 4.0.4 on 2022-06-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0009_delete_gift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=255)),
                ('gift_link', models.URLField(null=True)),
                ('comments', models.CharField(max_length=256, null=True)),
                ('party', models.ManyToManyField(to='imprezy.party')),
            ],
        ),
    ]
