# Generated by Django 4.0.4 on 2022-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0011_partygift_alter_gift_party_partygift_gift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='party',
            field=models.ManyToManyField(to='imprezy.party'),
        ),
    ]
