# Generated by Django 4.0.4 on 2022-06-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0014_alter_gift_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='party',
            field=models.ManyToManyField(through='imprezy.PartyGift', to='imprezy.party'),
        ),
    ]
