# Generated by Django 4.0.4 on 2022-06-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0016_alter_gift_party'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartyGift',
        ),
    ]
