# Generated by Django 4.0.4 on 2022-06-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0018_gift_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='availability',
        ),
        migrations.AlterField(
            model_name='gift',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='GiftReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('availability', models.BooleanField(default=False)),
                ('gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezy.gift')),
            ],
        ),
    ]
