# Generated by Django 4.0.4 on 2022-06-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0020_gift_availability_gift_reservation_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='party',
        ),
    ]
