# Generated by Django 4.0.4 on 2022-06-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0022_gift_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='availability',
        ),
    ]
