# Generated by Django 4.0.4 on 2022-06-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0023_remove_gift_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
