# Generated by Django 4.0.4 on 2022-06-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imprezy', '0024_gift_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='reservation_comment',
        ),
        migrations.CreateModel(
            name='GiftReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('reservation_comment', models.TextField(null=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imprezy.gift')),
            ],
        ),
    ]
